# Generated by Django 4.2.11 on 2025-11-01 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="Indirizzo IP del target",
                        unique=True,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        help_text="Hostname del sistema target",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descrizione del target"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("installing", "Installing"),
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Stato corrente del target",
                        max_length=20,
                    ),
                ),
                (
                    "firedog_version",
                    models.CharField(
                        blank=True,
                        help_text="Versione del pacchetto firedog installato",
                        max_length=50,
                    ),
                ),
                (
                    "ssh_port",
                    models.PositiveIntegerField(
                        default=22, help_text="Porta SSH del target"
                    ),
                ),
                (
                    "ssh_user",
                    models.CharField(
                        default="microcyber",
                        help_text="Utente SSH per la connessione",
                        max_length=100,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Ultimo contatto riuscito",
                        null=True,
                    ),
                ),
                (
                    "last_fetch",
                    models.DateTimeField(
                        blank=True, help_text="Ultimo fetch dati completato", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Ultimo messaggio di errore"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Target",
                "verbose_name_plural": "Targets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "last_seen"],
                        name="targets_tar_status_980528_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="targets_tar_ip_addr_3bd354_idx"
                    ),
                ],
            },
        ),
    ]
