# Generated by Django 4.2.11 on 2025-11-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_packets", models.BigIntegerField(default=0)),
                ("output_packets", models.BigIntegerField(default=0)),
                ("input_dropped", models.BigIntegerField(default=0)),
                ("output_dropped", models.BigIntegerField(default=0)),
                ("pcap_input_size", models.BigIntegerField(default=0)),
                ("pcap_output_size", models.BigIntegerField(default=0)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "db_table": "statistics",
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["target", "-collected_at"],
                        name="statistics_target__ae0143_idx",
                    )
                ],
            },
        ),
    ]
