# Generated by Django 4.2.11 on 2025-11-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0002_alert_statistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome del gruppo (es. 'Web Servers', 'DNS')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrizione del gruppo e del suo scopo"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Colore esadecimale per UI (es. #3b82f6)",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("database", "Database"),
                            ("globe", "Web/DNS"),
                            ("shield", "Security"),
                            ("hard-drive", "Storage"),
                            ("cloud", "Cloud"),
                            ("layers", "Application"),
                            ("box", "Generic"),
                        ],
                        default="server",
                        help_text="Icona per rappresentare il gruppo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "targets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Target appartenenti a questo gruppo",
                        related_name="groups",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target Group",
                "verbose_name_plural": "Target Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupRuleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descrittivo della regola", max_length=255
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("tcp", "TCP"),
                            ("udp", "UDP"),
                            ("icmp", "ICMP"),
                            ("all", "All"),
                        ],
                        default="tcp",
                        max_length=10,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True, help_text="Porta (opzionale per ICMP)", null=True
                    ),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP sorgente (opzionale, any se vuoto)",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ACCEPT", "Accept"),
                            ("DROP", "Drop"),
                            ("REJECT", "Reject"),
                        ],
                        default="ACCEPT",
                        max_length=10,
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Commento sulla regola"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Priorità di applicazione (più basso = più importante)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Gruppo a cui appartiene questo template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_templates",
                        to="targets.targetgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Rule Template",
                "verbose_name_plural": "Group Rule Templates",
                "ordering": ["group", "priority", "port"],
            },
        ),
    ]
