# Generated by Django 4.2.11 on 2025-11-13 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0003_targetgroup_groupruletemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhitelistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        help_text="Indirizzo IP o subnet CIDR (es. 192.168.1.0/24)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Descrizione dell'IP o subnet",
                        max_length=512,
                    ),
                ),
                (
                    "added_by",
                    models.CharField(
                        help_text="Utente che ha aggiunto l'entry", max_length=100
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Quando è stata aggiunta",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ultimo accesso rilevato da questo IP",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Numero di connessioni da questo IP"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Se disabilitato, l'IP non è più in whitelist",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Target su cui applicare la whitelist",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whitelist_entries",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whitelist Entry",
                "verbose_name_plural": "Whitelist Entries",
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["target", "is_active"],
                        name="targets_whi_target__385535_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="targets_whi_ip_addr_1be9df_idx"
                    ),
                    models.Index(
                        fields=["-added_at"], name="targets_whi_added_a_e6fada_idx"
                    ),
                ],
                "unique_together": {("target", "ip_address")},
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True,
                        help_text="Indirizzo IP bloccato",
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                (
                    "block_reason",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Block"),
                            ("threat_detected", "Threat Detected"),
                            ("port_scan", "Port Scanning"),
                            ("brute_force", "Brute Force Attack"),
                            ("syn_flood", "SYN Flood"),
                            ("ddos", "DDoS Attack"),
                            ("malware", "Malware Activity"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        help_text="Motivo del blocco",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrizione dettagliata del blocco"
                    ),
                ),
                (
                    "blocked_by",
                    models.CharField(
                        help_text="Utente o sistema che ha bloccato l'IP",
                        max_length=100,
                    ),
                ),
                (
                    "blocked_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Quando è stato bloccato",
                    ),
                ),
                (
                    "threat_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Score della minaccia (0-100)"
                    ),
                ),
                (
                    "packet_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Numero di pacchetti bloccati da questo IP"
                    ),
                ),
                (
                    "last_attempt",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ultimo tentativo di connessione",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scadenza blocco (null = permanente)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Se falso, il blocco è stato rimosso",
                    ),
                ),
                (
                    "unblocked_at",
                    models.DateTimeField(
                        blank=True, help_text="Quando è stato sbloccato", null=True
                    ),
                ),
                (
                    "unblocked_by",
                    models.CharField(
                        blank=True,
                        help_text="Utente che ha rimosso il blocco",
                        max_length=100,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Target su cui bloccare l'IP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_ips",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked IP",
                "verbose_name_plural": "Blocked IPs",
                "ordering": ["-blocked_at"],
                "indexes": [
                    models.Index(
                        fields=["target", "is_active"],
                        name="targets_blo_target__63f44e_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "is_active"],
                        name="targets_blo_ip_addr_86b7f3_idx",
                    ),
                    models.Index(
                        fields=["block_reason"], name="targets_blo_block_r_de03ac_idx"
                    ),
                    models.Index(
                        fields=["-blocked_at"], name="targets_blo_blocked_29ee0b_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="targets_blo_expires_0d9233_idx"
                    ),
                ],
                "unique_together": {("target", "ip_address")},
            },
        ),
    ]
