# Generated by Django 4.2.11 on 2025-11-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0004_whitelistentry_blockedip"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="gruppo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("web", "Web Server"),
                    ("db", "Database"),
                    ("dns", "DNS Server"),
                    ("storage", "Storage"),
                    ("mail", "Mail Server"),
                    ("backup", "Backup Server"),
                    ("monitoring", "Monitoring"),
                    ("proxy", "Proxy/Load Balancer"),
                    ("vpn", "VPN Gateway"),
                    ("firewall", "Firewall"),
                    ("application", "Application Server"),
                    ("cache", "Cache Server"),
                    ("queue", "Message Queue"),
                    ("other", "Altro"),
                    ("custom", "Personalizzato"),
                ],
                db_index=True,
                help_text="Gruppo logico del target per organizzazione e gestione regole",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="gruppo_custom",
            field=models.CharField(
                blank=True,
                help_text='Nome gruppo personalizzato se gruppo="custom"',
                max_length=100,
                null=True,
            ),
        ),
    ]
