# Generated by Django 4.2.11 on 2025-11-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0007_migrate_to_targetgroups"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        help_text="Hostname del target al momento del pull",
                        max_length=255,
                    ),
                ),
                (
                    "firedog_version",
                    models.CharField(
                        blank=True, help_text="Versione firewall-manager", max_length=50
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, help_text="Sistema operativo", max_length=255
                    ),
                ),
                (
                    "kernel_version",
                    models.CharField(
                        blank=True, help_text="Versione kernel", max_length=255
                    ),
                ),
                (
                    "uptime_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Uptime del sistema in secondi"
                    ),
                ),
                (
                    "input_packets",
                    models.BigIntegerField(
                        default=0, help_text="Totale pacchetti INPUT processati"
                    ),
                ),
                (
                    "output_packets",
                    models.BigIntegerField(
                        default=0, help_text="Totale pacchetti OUTPUT processati"
                    ),
                ),
                (
                    "forward_packets",
                    models.BigIntegerField(
                        default=0, help_text="Totale pacchetti FORWARD processati"
                    ),
                ),
                (
                    "pcap_input_dropped_bytes",
                    models.BigIntegerField(
                        default=0,
                        help_text="Dimensione file PCAP input dropped (bytes)",
                    ),
                ),
                (
                    "pcap_output_dropped_bytes",
                    models.BigIntegerField(
                        default=0,
                        help_text="Dimensione file PCAP output dropped (bytes)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="healthy",
                        help_text="Stato generale del firewall",
                        max_length=50,
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        help_text="Timestamp del JSON source (da target)"
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Quando è stato importato nel DB",
                    ),
                ),
                (
                    "raw_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON completo originale (opzionale)",
                        null=True,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Target che ha generato queste statistiche",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firewall_stats",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firewall Statistics",
                "verbose_name_plural": "Firewall Statistics",
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["target", "-collected_at"],
                        name="targets_fir_target__4cb1d3_idx",
                    ),
                    models.Index(
                        fields=["target", "-imported_at"],
                        name="targets_fir_target__eb350c_idx",
                    ),
                ],
                "unique_together": {("target", "collected_at")},
            },
        ),
    ]
