# Generated by Django 4.2.29 on 2026-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0009_target_connection_type_target_identity_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewallstats",
            name="dropped_input_packets",
            field=models.BigIntegerField(
                default=0, help_text="Pacchetti droppati in ingresso (LOG_INPUT_DROP)"
            ),
        ),
        migrations.AddField(
            model_name="firewallstats",
            name="dropped_output_packets",
            field=models.BigIntegerField(
                default=0, help_text="Pacchetti droppati in uscita (LOG_OUTPUT_DROP)"
            ),
        ),
    ]
