# Generated by Django 4.2.29 on 2026-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0010_firewallstats_dropped_input_packets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewallstats",
            name="protocols",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Counter per protocollo (tcp/udp/icmp in/out), cumulativi",
            ),
        ),
    ]
