# Generated by Django 4.2.29 on 2026-05-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0011_firewallstats_protocols"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewallstats",
            name="conntrack_count",
            field=models.IntegerField(
                default=0, help_text="Connessioni attive (nf_conntrack_count)"
            ),
        ),
        migrations.AddField(
            model_name="firewallstats",
            name="conntrack_max",
            field=models.IntegerField(
                default=0, help_text="Capacità massima conntrack (nf_conntrack_max)"
            ),
        ),
    ]
