# Generated by Django 4.2.29 on 2026-05-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0012_firewallstats_conntrack_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewallstats",
            name="network_flows_raw",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Snapshot peer remoti (ss -tun) — solo per debug, l'aggregato è in NetworkFlow",
            ),
        ),
        migrations.CreateModel(
            name="NetworkFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remote_ip",
                    models.GenericIPAddressField(
                        db_index=True,
                        help_text="IP remoto pubblico (no privati/loopback)",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ISO 3166-1 alpha-2 (es. 'US', 'IT'). Vuoto se lookup non disponibile.",
                        max_length=2,
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome del paese (cache da geoip2)",
                        max_length=128,
                    ),
                ),
                (
                    "times_seen",
                    models.BigIntegerField(
                        default=0,
                        help_text="Numero di snapshot in cui questo peer è stato osservato",
                    ),
                ),
                (
                    "last_ports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ultime porte remote viste (dedupe, max 10)",
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Target che ha visto il flusso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_flows",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Flow",
                "verbose_name_plural": "Network Flows",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["target", "country_code"],
                        name="targets_net_target__2f670a_idx",
                    ),
                    models.Index(
                        fields=["country_code"], name="targets_net_country_9f00e1_idx"
                    ),
                    models.Index(
                        fields=["-last_seen"], name="targets_net_last_se_1e08ee_idx"
                    ),
                ],
                "unique_together": {("target", "remote_ip")},
            },
        ),
    ]
