# Generated by Django 4.2.29 on 2026-08-29 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0013_firewallstats_network_flows_raw_networkflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome del device (es. eth0, ens192)", max_length=50
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP assegnato a questa interfaccia (può essere assente se down)",
                        null=True,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        help_text="MAC address dell'interfaccia",
                        max_length=17,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="True se corrisponde a Target.ip_address/mac_address (interfaccia di pairing)",
                    ),
                ),
                (
                    "is_up",
                    models.BooleanField(
                        default=True,
                        help_text="Stato operativo riportato dall'ultimo snapshot",
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Target a cui appartiene questa interfaccia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Interface",
                "verbose_name_plural": "Network Interfaces",
                "ordering": ["target", "-is_primary", "name"],
                "indexes": [
                    models.Index(
                        fields=["target", "-is_primary"],
                        name="targets_net_target__312ff4_idx",
                    )
                ],
                "unique_together": {("target", "name")},
            },
        ),
    ]
