# Generated by Django 4.2.29 on 2026-08-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0014_networkinterface"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkinterface",
            name="rx_bytes",
            field=models.BigIntegerField(
                default=0, help_text="Byte ricevuti (cumulativo)"
            ),
        ),
        migrations.AddField(
            model_name="networkinterface",
            name="rx_packets",
            field=models.BigIntegerField(
                default=0, help_text="Pacchetti ricevuti (cumulativo)"
            ),
        ),
        migrations.AddField(
            model_name="networkinterface",
            name="tx_bytes",
            field=models.BigIntegerField(
                default=0, help_text="Byte trasmessi (cumulativo)"
            ),
        ),
        migrations.AddField(
            model_name="networkinterface",
            name="tx_packets",
            field=models.BigIntegerField(
                default=0, help_text="Pacchetti trasmessi (cumulativo)"
            ),
        ),
    ]
