# Generated by Django 4.2.11 on 2026-01-15 09:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0009_target_connection_type_target_identity_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(help_text="SHA512 hash dell'API key", max_length=128, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Solo una chiave può essere attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Scadenza chiave (null = mai)', null=True)),
                ('created_by', models.CharField(help_text='Utente che ha creato la chiave', max_length=100)),
            ],
            options={
                'verbose_name': 'Agent API Key',
                'verbose_name_plural': 'Agent API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentConnection',
            fields=[
                ('target', models.OneToOneField(help_text='Target connesso', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent_connection', serialize=False, to='targets.target')),
                ('websocket_channel', models.CharField(help_text='Django Channels channel name', max_length=255)),
                ('is_online', models.BooleanField(db_index=True, default=True, help_text='Agent connesso e attivo')),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Ultimo heartbeat ricevuto')),
                ('heartbeat_interval', models.PositiveIntegerField(default=30, help_text='Intervallo heartbeat in secondi')),
                ('system_info', models.JSONField(blank=True, help_text="Statistiche sistema dall'ultimo heartbeat", null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, help_text="Quando l'agent si è disconnesso", null=True)),
            ],
            options={
                'verbose_name': 'Agent Connection',
                'verbose_name_plural': 'Agent Connections',
            },
        ),
        migrations.CreateModel(
            name='PairingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Agent'), ('verifying_api', 'Verifying API Key'), ('verifying_hash', 'Verifying Identity Hash'), ('success', 'Pairing Success'), ('failed', 'Pairing Failed'), ('expired', 'Session Expired')], db_index=True, default='waiting', max_length=20)),
                ('phase_1_verified', models.BooleanField(default=False, help_text='API key verificata')),
                ('phase_2_verified', models.BooleanField(default=False, help_text='Identity hash verificato')),
                ('agent_ip', models.GenericIPAddressField(blank=True, help_text="IP ricevuto dall'agent", null=True)),
                ('agent_hostname', models.CharField(blank=True, help_text="Hostname ricevuto dall'agent", max_length=255)),
                ('agent_mac', models.CharField(blank=True, help_text="MAC address ricevuto dall'agent", max_length=17)),
                ('error_message', models.TextField(blank=True, help_text='Messaggio di errore in caso di fallimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(help_text='Scadenza sessione (3 minuti)')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Quando il pairing è stato completato', null=True)),
                ('target', models.ForeignKey(help_text='Target da connettere', on_delete=django.db.models.deletion.CASCADE, related_name='pairing_sessions', to='targets.target')),
            ],
            options={
                'verbose_name': 'Pairing Session',
                'verbose_name_plural': 'Pairing Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('command_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID univoco del comando', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('add_rule', 'Add Firewall Rule'), ('remove_rule', 'Remove Firewall Rule'), ('sync_rules', 'Sync All Rules'), ('block_ip', 'Block IP'), ('unblock_ip', 'Unblock IP'), ('update_config', 'Update Configuration'), ('check_integrity', 'Check File Integrity')], help_text='Azione da eseguire', max_length=50)),
                ('payload', models.JSONField(help_text='Parametri del comando')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Agent'), ('executing', 'Executing'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, help_text='Risultato esecuzione comando', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Messaggio di errore')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Timeout comando in secondi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(help_text='Target su cui eseguire il comando', on_delete=django.db.models.deletion.CASCADE, related_name='agent_commands', to='targets.target')),
            ],
            options={
                'verbose_name': 'Agent Command',
                'verbose_name_plural': 'Agent Commands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Quando l'heartbeat è stato ricevuto")),
                ('cpu_percent', models.FloatField(default=0)),
                ('memory_percent', models.FloatField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_recv', models.BigIntegerField(default=0)),
                ('active_rules_count', models.PositiveIntegerField(default=0)),
                ('blocked_ips_count', models.PositiveIntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, help_text='Dati completi heartbeat', null=True)),
                ('target', models.ForeignKey(help_text="Target che ha inviato l'heartbeat", on_delete=django.db.models.deletion.CASCADE, related_name='agent_heartbeats', to='targets.target')),
            ],
            options={
                'verbose_name': 'Agent Heartbeat',
                'verbose_name_plural': 'Agent Heartbeats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target', '-timestamp'], name='agent_manag_target__be72fd_idx')],
            },
        ),
    ]
