# Generated by Django 4.2.11 on 2026-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentapikey",
            name="encrypted_key",
            field=models.TextField(
                blank=True,
                help_text="API key criptata (recuperabile con password admin)",
                null=True,
            ),
        ),
    ]
