# Generated by Django 4.2.29 on 2026-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agent_manager",
            "0003_merge_0001_add_encrypted_key_field_0002_alter_agentapikey_encrypted_key",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agentheartbeat",
            name="disk_total_kb",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentheartbeat",
            name="disk_used_kb",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentheartbeat",
            name="load_avg_15m",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="agentheartbeat",
            name="load_avg_1m",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="agentheartbeat",
            name="load_avg_5m",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="agentheartbeat",
            name="memory_total_kb",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentheartbeat",
            name="memory_used_kb",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentheartbeat",
            name="uptime_seconds",
            field=models.BigIntegerField(default=0),
        ),
    ]
