# Generated by Django 4.2.11 on 2025-11-15 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Chiave univoca dell'impostazione",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.JSONField(help_text="Valore dell'impostazione (JSON)"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Generale"),
                            ("appearance", "Aspetto"),
                            ("notifications", "Notifiche"),
                            ("security", "Sicurezza"),
                            ("monitoring", "Monitoraggio"),
                        ],
                        default="general",
                        help_text="Categoria dell'impostazione",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrizione dell'impostazione"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Se True, visibile a tutti gli utenti autenticati",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseCleanupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cleanup_type",
                    models.CharField(
                        choices=[
                            ("audit_logs", "Audit Logs"),
                            ("threat_logs", "Threat Logs"),
                            ("statistics", "Statistics"),
                            ("discovered_hosts", "Discovered Hosts"),
                            ("all", "All"),
                        ],
                        help_text="Tipo di pulizia eseguita",
                        max_length=50,
                    ),
                ),
                (
                    "records_deleted",
                    models.IntegerField(
                        default=0, help_text="Numero di record eliminati"
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(help_text="Giorni di retention applicati"),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Se True, operazione completata con successo",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Messaggio di errore se success=False"
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleanup_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Database Cleanup Log",
                "verbose_name_plural": "Database Cleanup Logs",
                "db_table": "database_cleanup_logs",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="SSHKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descrittivo della chiave", max_length=255
                    ),
                ),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("ed25519", "Ed25519"),
                            ("rsa", "RSA"),
                            ("ecdsa", "ECDSA"),
                        ],
                        default="ed25519",
                        help_text="Tipo di chiave SSH",
                        max_length=20,
                    ),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        blank=True,
                        help_text="Dimensione chiave RSA (bit)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2048),
                            django.core.validators.MaxValueValidator(8192),
                        ],
                    ),
                ),
                ("public_key", models.TextField(help_text="Chiave pubblica SSH")),
                (
                    "private_key",
                    models.TextField(help_text="Chiave privata SSH (encrypted)"),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="Fingerprint SHA256 della chiave",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Globale"),
                            ("group", "Gruppo"),
                            ("target", "Target"),
                        ],
                        default="global",
                        help_text="Ambito di utilizzo della chiave",
                        max_length=20,
                    ),
                ),
                (
                    "scope_value",
                    models.CharField(
                        blank=True,
                        help_text="Valore dello scope (nome gruppo o ID target)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, la chiave non viene utilizzata",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="Ultimo utilizzo della chiave", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ssh_keys_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SSH Key",
                "verbose_name_plural": "SSH Keys",
                "db_table": "ssh_keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "scope_value"],
                        name="ssh_keys_scope_52bf7e_idx",
                    ),
                    models.Index(
                        fields=["fingerprint"], name="ssh_keys_fingerp_769fdf_idx"
                    ),
                ],
            },
        ),
    ]
