# Generated by Django 4.2.11 on 2025-11-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_notification_models"),
    ]

    operations = []
