# Generated by Django 4.2.11 on 2025-11-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_notification_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notificatio_alert_t_c828e7_idx",
            old_name="notificatio_alert_t_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notificatio_target__63f839_idx",
            old_name="notificatio_target_idx",
        ),
    ]
