# Generated by Django 4.2.11 on 2026-04-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "settings",
            "0003_rename_notificatio_alert_t_idx_notificatio_alert_t_c828e7_idx_and_more",
        ),
        (
            "settings",
            "0003_rename_notificatio_alert_t_idx_notificatio_alert_t_c828e7_idx_and_more2",
        ),
    ]

    operations = []
