# Generated by Django 4.2.30 on 2026-08-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_merge_20260420_2203"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SSHKey",
        ),
    ]
