# Generated by Django 4.2.11 on 2025-11-01 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('INPUT', 'INPUT'), ('OUTPUT', 'OUTPUT'), ('FORWARD', 'FORWARD')], db_index=True, help_text='Chain iptables', max_length=10)),
                ('rule_number', models.PositiveIntegerField(blank=True, help_text='Numero della regola nella chain', null=True)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('all', 'ALL')], default='tcp', help_text='Protocollo di rete', max_length=10)),
                ('port', models.PositiveIntegerField(blank=True, help_text='Porta di destinazione', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='IP sorgente', null=True, validators=[django.core.validators.validate_ipv46_address])),
                ('dest_ip', models.GenericIPAddressField(blank=True, help_text='IP destinazione', null=True, validators=[django.core.validators.validate_ipv46_address])),
                ('action', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('DROP', 'DROP'), ('REJECT', 'REJECT')], default='ACCEPT', help_text='Azione della regola', max_length=10)),
                ('comment', models.CharField(blank=True, help_text='Commento descrittivo della regola', max_length=256)),
                ('is_custom', models.BooleanField(db_index=True, default=True, help_text='Indica se è una regola custom o predefinita')),
                ('is_synced', models.BooleanField(default=False, help_text='Indica se la regola è sincronizzata sul target')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(help_text='Target su cui applicare la regola', on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to='targets.target')),
            ],
            options={
                'verbose_name': 'Firewall Rule',
                'verbose_name_plural': 'Firewall Rules',
                'ordering': ['target', 'chain', 'rule_number'],
                'indexes': [models.Index(fields=['target', 'chain'], name='rules_firew_target__4276be_idx'), models.Index(fields=['target', 'is_custom'], name='rules_firew_target__0e48ab_idx'), models.Index(fields=['is_synced'], name='rules_firew_is_sync_c2fb14_idx')],
            },
        ),
    ]
