# Generated by Django 4.2.29 on 2026-05-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0009_target_connection_type_target_identity_hash_and_more"),
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewallrule",
            name="group_origin",
            field=models.ForeignKey(
                blank=True,
                help_text="Gruppo da cui questa rule è stata propagata. NULL = rule creata direttamente sul singolo target.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_rules",
                to="targets.targetgroup",
            ),
        ),
    ]
