# Generated by Django 4.2.29 on 2026-05-19 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0009_target_connection_type_target_identity_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0002_firewallrule_group_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallRuleBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (
                                "group_apply_overwrite",
                                "Pre apply group rules (overwrite)",
                            ),
                            ("manual", "Manual backup"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        help_text="Motivo del backup",
                        max_length=40,
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        default=list,
                        help_text="Lista di dict serializzati delle FirewallRule esistenti al momento del backup. Schema per dict: chain, rule_number, protocol, port, source_ip, dest_ip, action, comment, is_custom, is_synced, group_origin_id.",
                    ),
                ),
                ("rules_count", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "related_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gruppo che ha causato il backup (se applicabile)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_rule_backups",
                        to="targets.targetgroup",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Target di cui sono state salvate le rule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_backups",
                        to="targets.target",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utente che ha avviato l'azione (se applicabile)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firewall_rule_backups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Firewall Rule Backup",
                "verbose_name_plural": "Firewall Rule Backups",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target", "-created_at"],
                        name="rules_firew_target__e362fd_idx",
                    )
                ],
            },
        ),
    ]
