# Generated by Django 4.2.29 on 2026-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0003_firewallrulebackup"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewallrule",
            name="interface",
            field=models.CharField(
                blank=True,
                help_text="NIC specifica su cui applicare la regola (es. eth0). Vuoto = tutto l'host (comportamento storico, invariato per le regole esistenti). Applicata come -i per chain INPUT, -o per OUTPUT.",
                max_length=50,
            ),
        ),
    ]
