# Generated by Django 4.2.11 on 2025-11-01 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscoveredHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True,
                        help_text="Indirizzo IP scoperto",
                        unique=True,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        help_text="Indirizzo MAC (formato XX:XX:XX:XX:XX:XX)",
                        max_length=17,
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        help_text="Hostname risolto (se disponibile)",
                        max_length=255,
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Vendor dell'interfaccia di rete",
                        max_length=255,
                    ),
                ),
                (
                    "network",
                    models.GenericIPAddressField(
                        blank=True, help_text="Rete di appartenenza", null=True
                    ),
                ),
                (
                    "netmask",
                    models.CharField(
                        blank=True, help_text="Netmask della rete", max_length=15
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Quando l'host è stato scoperto",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Ultimo scan in cui l'host è stato visto",
                    ),
                ),
                (
                    "scan_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Numero di volte che l'host è stato visto negli scan",
                    ),
                ),
                (
                    "is_alive",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Host ancora attivo nell'ultimo scan",
                    ),
                ),
                (
                    "is_imported",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Host importato come target",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Note sull'host scoperto"),
                ),
            ],
            options={
                "verbose_name": "Discovered Host",
                "verbose_name_plural": "Discovered Hosts",
                "ordering": ["-last_seen", "ip_address"],
                "indexes": [
                    models.Index(
                        fields=["is_alive", "is_imported"],
                        name="discovery_d_is_aliv_3b6160_idx",
                    ),
                    models.Index(
                        fields=["network"], name="discovery_d_network_7f1856_idx"
                    ),
                    models.Index(
                        fields=["discovered_at"], name="discovery_d_discove_7b06c2_idx"
                    ),
                ],
            },
        ),
    ]
