# Generated by Django 4.2.29 on 2026-07-02 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descrittivo della chiave (es. 'claude-desktop')",
                        max_length=100,
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="Prefisso visibile della chiave per identificarla (es. fd_a1B2c3D4)",
                        max_length=16,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 esadecimale della chiave completa",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False = chiave revocata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scadenza opzionale della chiave",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ultimo utilizzo (aggiornato best-effort)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utente proprietario: la chiave ne eredita ruolo e permessi",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP API Key",
                "verbose_name_plural": "MCP API Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
