# Generated by Django 4.2.11 on 2025-11-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User agent del client",
                max_length=512,
                null=True,
            ),
        ),
    ]
