# Generated by Django 4.2.11 on 2025-11-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("install", "Install"),
                    ("uninstall", "Uninstall"),
                    ("rule_add", "Rule Add"),
                    ("rule_remove", "Rule Remove"),
                    ("fetch", "Fetch Data"),
                    ("scan", "Network Scan"),
                    ("approve", "Approve Change"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("error", "Error"),
                ],
                db_index=True,
                help_text="Tipo di azione eseguita",
                max_length=50,
            ),
        ),
    ]
